[workspace]
members = ["blackbird", "blackbird-core", "blackbird-subsonic"]
resolver = "2"

[workspace.dependencies]
serde = { version = "1.0.218", features = ["derive"] }
tracing = "0.1.41"
tracing-subscriber = "0.3.19"

[profile.dev.package.image]
opt-level = 3

[profile.release.package.image]
opt-level = 3
