[package]
name = "blackbird-id3mover"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = { workspace = true }

clap = { version = "4.5.40", features = ["derive"] }
sanitize-filename = "0.6.0"
symphonia = "0.5.4"
walkdir = "2.5.0"
