[package]
name = "blackbird-subsonic"
version = "0.1.0"
edition = "2024"

[dependencies]
data-encoding = "2.8.0"
md5 = "0.7.0"
reqwest = "0.12.12"

rand = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }

[features]
default = ["opensubsonic"]
opensubsonic = []
