[package]
name = "blackbird-subsonic"
version = "0.1.0"
edition = "2021"

[dependencies]
data-encoding = "2.8.0"
md5 = "0.7.0"
rand = "0.9.0"
reqwest = "0.12.12"

serde = { workspace = true }
serde_json = "1.0.139"
