[package]
name = "blackbird-spotcheck"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = { version = "0.4.41", features = ["serde"] }

anyhow = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
